const resData = [
  {
    id: 1,
    name: "Classic Margherita Pizza",
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Italian",
    costForTwo: 30000,
    tags: ["Pizza", "Italian"],
    userId: 166,
    image: "https://cdn.dummyjson.com/recipe-images/1.webp",
    rating: 4.6,
    reviewCount: 98,
    mealType: ["Dinner"],
  },
  {
    id: 2,
    name: "Vegetarian Stir-Fry",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: "Medium",
    cuisine: "Asian",
    costForTwo: 40000,
    tags: ["Vegetarian", "Stir-fry", "Asian"],
    userId: 143,
    image: "https://cdn.dummyjson.com/recipe-images/2.webp",
    rating: 4.7,
    reviewCount: 26,
    mealType: ["Lunch"],
  },
  {
    id: 3,
    name: "Chocolate Chip Cookies",
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 24,
    difficulty: "Easy",
    cuisine: "American",
    costForTwo: 15000,
    tags: ["Cookies", "Dessert", "Baking"],
    userId: 34,
    image: "https://cdn.dummyjson.com/recipe-images/3.webp",
    rating: 3.9,
    reviewCount: 13,
    mealType: ["Snack", "Dessert"],
  },
  {
    id: 4,
    name: "Chicken Alfredo Pasta",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Italian",
    costForTwo: 500,
    tags: ["Pasta", "Chicken"],
    userId: 136,
    image: "https://cdn.dummyjson.com/recipe-images/4.webp",
    rating: 4.9,
    reviewCount: 82,
    mealType: ["Lunch", "Dinner"],
  },
  {
    id: 5,
    name: "Mango Salsa Chicken",
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: "Easy",
    cuisine: "Mexican",
    costForTwo: 380,
    tags: ["Chicken", "Salsa"],
    userId: 26,
    image: "https://cdn.dummyjson.com/recipe-images/5.webp",
    rating: 4.9,
    reviewCount: 63,
    mealType: ["Dinner"],
  },
  {
    id: 6,
    name: "Quinoa Salad with Avocado",
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Mediterranean",
    costForTwo: 280,
    tags: ["Salad", "Quinoa"],
    userId: 197,
    image: "https://cdn.dummyjson.com/recipe-images/6.webp",
    rating: 4.4,
    reviewCount: 59,
    mealType: ["Lunch", "Side Dish"],
  },
  {
    id: 7,
    name: "Tomato Basil Bruschetta",
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 6,
    difficulty: "Easy",
    cuisine: "Italian",
    costForTwo: 120,
    tags: ["Bruschetta", "Italian"],
    userId: 137,
    image: "https://cdn.dummyjson.com/recipe-images/7.webp",
    rating: 4.7,
    reviewCount: 95,
    mealType: ["Appetizer"],
  },
  {
    id: 8,
    name: "Beef and Broccoli Stir-Fry",
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Asian",
    costForTwo: 380,
    tags: ["Beef", "Stir-fry", "Asian"],
    userId: 18,
    image: "https://cdn.dummyjson.com/recipe-images/8.webp",
    rating: 4.7,
    reviewCount: 58,
    mealType: ["Dinner"],
  },
  {
    id: 9,
    name: "Caprese Salad",
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    difficulty: "Easy",
    cuisine: "Italian",
    costForTwo: 200,
    tags: ["Salad", "Caprese"],
    userId: 128,
    image: "https://cdn.dummyjson.com/recipe-images/9.webp",
    rating: 4.6,
    reviewCount: 82,
    mealType: ["Lunch"],
  },
  {
    id: 10,
    name: "Shrimp Scampi Pasta",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: "Medium",
    cuisine: "Italian",
    costForTwo: 400,
    tags: ["Pasta", "Shrimp"],
    userId: 114,
    image: "https://cdn.dummyjson.com/recipe-images/10.webp",
    rating: 3.3,
    reviewCount: 5,
    mealType: ["Dinner"],
  },
  {
    id: 11,
    name: "Chicken Biryani",
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    servings: 6,
    difficulty: "Medium",
    cuisine: "Pakistani",
    costForTwo: 550,
    tags: ["Biryani", "Chicken", "Main course", "Indian", "Pakistani", "Asian"],
    userId: 133,
    image: "https://cdn.dummyjson.com/recipe-images/11.webp",
    rating: 5,
    reviewCount: 32,
    mealType: ["Lunch", "Dinner"],
  },
  {
    id: 12,
    name: "Chicken Karahi",
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Pakistani",
    costForTwo: 420,
    tags: ["Chicken", "Karahi", "Main course", "Indian", "Pakistani", "Asian"],
    userId: 49,
    image: "https://cdn.dummyjson.com/recipe-images/12.webp",
    rating: 4.8,
    reviewCount: 68,
    mealType: ["Lunch", "Dinner"],
  },
  {
    id: 13,
    name: "Aloo Keema",
    prepTimeMinutes: 25,
    cookTimeMinutes: 35,
    servings: 5,
    difficulty: "Medium",
    cuisine: "Pakistani",
    costForTwo: 380,
    tags: ["Keema", "Potatoes", "Main course", "Pakistani", "Asian"],
    userId: 152,
    image: "https://cdn.dummyjson.com/recipe-images/13.webp",
    rating: 4.6,
    reviewCount: 53,
    mealType: ["Lunch", "Dinner"],
  },
  {
    id: 14,
    name: "Chapli Kebabs",
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Pakistani",
    costForTwo: 320,
    tags: ["Kebabs", "Beef", "Indian", "Pakistani", "Asian"],
    userId: 152,
    image: "https://cdn.dummyjson.com/recipe-images/14.webp",
    rating: 4.7,
    reviewCount: 98,
    mealType: ["Lunch", "Dinner", "Snacks"],
  },
  {
    id: 15,
    name: "Saag (Spinach) with Makki di Roti",
    prepTimeMinutes: 40,
    cookTimeMinutes: 30,
    servings: 3,
    difficulty: "Medium",
    cuisine: "Pakistani",
    costForTwo: 280,
    tags: ["Saag", "Roti", "Main course", "Indian", "Pakistani", "Asian"],
    userId: 43,
    image: "https://cdn.dummyjson.com/recipe-images/15.webp",
    rating: 3.3,
    reviewCount: 86,
    mealType: ["Breakfast", "Lunch", "Dinner"],
  },
  {
    id: 16,
    name: "Japanese Ramen Soup",
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: "Medium",
    cuisine: "Japanese",
    costForTwo: 480,
    tags: ["Ramen", "Japanese", "Soup", "Asian"],
    userId: 85,
    image: "https://cdn.dummyjson.com/recipe-images/16.webp",
    rating: 4.9,
    reviewCount: 38,
    mealType: ["Dinner"],
  },
  {
    id: 17,
    name: "Moroccan Chickpea Tagine",
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Moroccan",
    costForTwo: 320,
    tags: ["Tagine", "Chickpea", "Moroccan"],
    userId: 207,
    image: "https://cdn.dummyjson.com/recipe-images/17.webp",
    rating: 4.5,
    reviewCount: 50,
    mealType: ["Dinner"],
  },
  {
    id: 18,
    name: "Korean Bibimbap",
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Medium",
    cuisine: "Korean",
    costForTwo: 550,
    tags: ["Bibimbap", "Korean", "Rice"],
    userId: 121,
    image: "https://cdn.dummyjson.com/recipe-images/18.webp",
    rating: 4.9,
    reviewCount: 56,
    mealType: ["Dinner"],
  },
];

export default resData;
